### ISSUE TITLE
Request: unicode character class implementations

### ISSUE THREAD

**Issue by hachi8833** [dlclark/regexp2#2]
Thank you very much for the porting!

I checked your library and found that most unicode character classes have not been implemented yet.

Reference: http://www.fileformat.info/info/unicode/category/index.htm

Looks like fundamental character categories, such as `[\p{P}]` (= any punctuations), are available:
```go
package main

import (
	"fmt"

	"github.com/dlclark/regexp2"
)

func main() {
	re := regexp2.MustCompile(`(?<=[カキケコ\p{Po}])ん+`, 0) // works
	isMatch, err := re.FindStringMatch(`ブック。んん`)
	if err == nil {
		fmt.Println(isMatch)
	}
}

```

But most advanced [character classes (block)](http://www.fileformat.info/info/unicode/block/index.htm) such as `[\p{Katakana}]` have not been implemented:

```go
package main

import (
	"fmt"

	"github.com/dlclark/regexp2"
)

func main() {
	re := regexp2.MustCompile(`(?<=[カキケコ\p{Katakana}])ん+`, 0) // panic with [\p{Katakana}]
	isMatch, err := re.FindStringMatch(`ブック。んん`)
	if err == nil {
		fmt.Println(isMatch)
	}
}
```
The sample code above causes `panic: not impelemented`.

I hope you'd implement them in a future.

**Comment by dlclark** [comment]
Thanks for the request! 

I've attempted a basic feature for this -- check out tag v1.0.1 (519dd65), it includes a basic smoke test.  Apparently the longer names (like "Katakana") aren't technically Unicode categories, but are instead "Scripts."  Because of this the go runtime stores them in a separate list so they were unavailable to the `\p{}` syntax.  I've updated the regexp2 code to join the `unicode.Categories` and `unicode.Scripts` maps so now all the known unicode scripts should work with `\p` as expected.

Unfortunately I don't know enough about your example pattern or the characters involved to know the proper behavior you're expecting.  If this new version doesn't work for you please give me a simple test similar to `TestUnicodeScriptSets` that doesn't pass and I'll fix it up.

Once again, thanks for the heads up.  My day-to-day is all ASCII so the unicode matching is an area that I need as much help as I can get!

**Comment by hachi8833** [comment]
Tried v1.0.1 and worked fine for my small test. Thank you very much for your kindness and quick update!
Now I can use most of .NET regexp syntax I need. (Yes, the names are actually 'Scripts' as you specified :-)

---------------------------
FYI
I've been looking for regex engine for Go language that meets the following requirement:
- 'Scripts' such as 'Katakana' or 'Hiragana' are available as character classes
- Look-ahead/behind (both positive and negative) with quantifiers, such as `(?<=[a-zA-Z])blahblar(?=[a-zA-Z])` or `(?<![a-zA-Z])blahblar(?![a-zA-Z])`, are fully supported (I recognize that such expressions might be inefficient in some cases, but it's been very convenient for me in .NET environment)

I've been familiar with .NET regex with the advanced features, which are missing in almost all other regex engines except '[onigmo](https://goo.gl/i5lEYJ)'. While onigmo is very fast and almost equivalent to .NET framework, it is available only for ruby by now. 

Thus I adopted [rubex](https://goo.gl/vinFHH) library for my Go app by now, but the engine for rubex is [oniguruma](https://goo.gl/Fvo0Iy), the previous version of onigmo. Full look ahead/behind with quantifier is missing in oniguruma.

Once I tried to port onigmo to rubex, but it is cgo-based (bridging c and go) and very hacky for me to implement. Instead, your regexp2 is based on [c# .NET code](https://goo.gl/6yXOW2) and much cleaner than rubex. 

Your porting regexp2 from .NET source is a good news from heaven for me. I really appreciate your work. :-)
