### ISSUE TITLE
Bulk replace

### ISSUE THREAD

**Issue by hachi8833** [dlclark/regexp2#3]
Hello,

I'd just like to ask you if you have any plans to implement bulk replace functions to your regexp2 as the Go standard regex?
    https://golang.org/pkg/regexp/#Regexp.ReplaceAll

-     func (re *Regexp) ReplaceAll(src, repl []byte) []byte
-     func (re *Regexp) ReplaceAllFunc(src []byte, repl func([]byte) []byte) []byte
-     func (re *Regexp) ReplaceAllLiteral(src, repl []byte) []byte
-     func (re *Regexp) ReplaceAllLiteralString(src, repl string) string
-     func (re *Regexp) ReplaceAllString(src, repl string) string
-     func (re *Regexp) ReplaceAllStringFunc(src string, repl func(string) string) string

Thank you,

**Comment by dlclark** [comment]
Is there a specific behavior you need?

In general the regexp2 engine uses `[]rune` instead of `[]byte` but those are much less common than just having a string, so I left those overloads out in a few places.

The existing replace function in regexp2 is:
```go
func (re *Regexp) Replace(input, replacement string, startAt, count int) (string, error)
```
You can see from the example usage in `replace_test.go` that it most aligns with `ReplaceAllString`.  That was the only replacer I needed so I stopped after implementing it.  
 
If you need the literal version (without match expansion) or the function replacer let me know and I'll look into it.

**Comment by hachi8833** [comment]
Thank you very much for answering my question!
I should've noticed that `-1` for `count` works as normal bulk replace. I'd use current Replace function as that.

FYI: this is a quick update I created just now for my interest, removing startAt and count. Ignore this. 
https://github.com/hachi8833/regexp2/tree/replaceallstring

**Comment by hachi8833** [comment]
Hello again, 

After that, I found that I need 'function replacer' version of Replace function, like ReplaceAllStringFunc.
I'd be very glad if you'd kindly implement that. How about this?

**Comment by dlclark** [comment]
No problem, I'll poke around to see how easy this is.

**Comment by dlclark** [comment]
Turns out, it was pretty easy.  It's based on the .NET version of the Replace function, so the replacement function `MatchEvaluator` takes a full `Match` instead of just a `string` as input.

```go
func (re *Regexp) ReplaceFunc(input string, evaluator MatchEvaluator, startAt, count int) (string, error)
```

**Comment by hachi8833** [comment]
Thank you very much for your kindness with explanations! I'll look into it.
