### ISSUE TITLE
A bug when .* in the content  to match

### ISSUE THREAD

**Issue by wgplt** [dlclark/regexp2#49]
The code that caused the error： 

![image](https://user-images.githubusercontent.com/54103241/165486328-7489681c-c7fe-425d-bfb4-5e21ad2d0100.png)

Why nil ？

This should be the right result：

![image](https://user-images.githubusercontent.com/54103241/165486579-f7410061-e412-4981-b419-fec4009b0e64.png)

**Sample code：**

`package main

import (
	"fmt"

	"github.com/dlclark/regexp2"
)

func main() {

	r, err := regexp2.Compile(`(?<=1234\.\*56).*(?=890)`, regexp2.Compiled)

	if err != nil {
		panic(err)
	}

	m, err := r.FindStringMatch(`1234.*567890`)
	if err != nil {
		panic(err)
	}

	fmt.Println(m)
}`

**Comment by dlclark** [comment]
This was a heck of a bug!

Basically it required a specific shape to string literals within the pattern broken up with escape sequences just right so that when the pattern parser concatenated them all it re-used the underlying rune slice.  The rune slice was an extract from the pattern itself, so the `append` calls were smashing the contents of the pattern accidentally.  This meant the pattern was being parsed into a weird state and wouldn't match what you wanted.  

The fix was to copy the runes from the pattern into a new slice instead of just slicing from the pattern itself. A simple fix after hours of debugging.
