### ISSUE TITLE
The matching results of strings containing Chinese characters are incorrect

### ISSUE THREAD

**Issue by sniperking1234** [dlclark/regexp2#64]
```go
package main

import (
	"fmt"
	"github.com/dlclark/regexp2"
	"regexp"
)

func main() {
	str := `我的邮箱是bwgjs2019@163.com和wzy82cn@163.com`
	reg := `\b(((([*+\-=?^_{|}~\w])|([*+\-=?^_{|}~\w][*+\-=?^_{|}~\.\w]{0,}[*+\-=?^_{|}~\w]))[@]\w+([-.]\w+)*\.[A-Za-z]{2,8}))\b`
	re, _ := regexp.Compile(reg)
	re2, _ := regexp2.Compile(reg, 0)
	fmt.Println(re.FindAllString(str, -1))
	result, _ := re2.FindStringMatch(str)
	fmt.Println(result.String())
}
```
The result of regexp is `bwgjs2019@163.com wzy82cn@163.com`, but the regexp2 result is `163.com和wzy82cn@163.com`.

**Comment by dlclark** [comment]
After more digging I've figure out the difference.  In the `regexp` package `\b` is only a word boundary for simple ascii `[A-Za-z0-9_]` so the initial Chinese characters are not considered a word boundary. Since `regexp2` (and Rust, Python, and C#) uses full unicode definition for "letter" to define `\b` the initial Chinese characters are considered a word boundary.

If you expand `\b` to the full definition (`(?<!\w)(?=\w)|(?<=\w)(?!\w)`) and then expand the `\w` to the simplified `regexp` package definition `A-Za-z0-9_` then you end up with this regex which will make `regexp2` capture similarly to `regexp`:

`((?<![A-Za-z0-9_])(?=[A-Za-z0-9_])|(?<=[A-Za-z0-9_])(?![A-Za-z0-9_]))(((([*+\-=?^_{|}~\w])|([*+\-=?^_{|}~\w][*+\-=?^_{|}~\.\w]{0,}[*+\-=?^_{|}~\w]))[@]\w+([-.]\w+)*\.[A-Za-z]{2,8}))((?<![A-Za-z0-9_])(?=[A-Za-z0-9_])|(?<=[A-Za-z0-9_])(?![A-Za-z0-9_]))`

FYI, since the above regex uses look-arounds it's not compatible with the `regexp` package.
