### ISSUE TITLE
No support for \p{unicode char class} that is supported by the Go stdlib regex package

### ISSUE THREAD

**Issue by kovidgoyal** [dlclark/regexp2#65]
Extract from https://pkg.go.dev/regexp/syntax

```
\pN            Unicode character class (one-letter name)
\p{Greek}      Unicode character class
\PN            negated Unicode character class (one-letter name)
\P{Greek}      negated Unicode character class
```

I imagine this could be implemented in RE2 compat mode.

**Comment by dlclark** [comment]
The `\p{N}` syntax is already supported, but I'll need to add `\pN` support. Since the current behavior for this syntax is a compile error I'm considering adding it as default behavior and not putting it behind the RE2 flag.  It's hard to imagine that anybody is depending on the existing compile error if they used the `\pN` syntax and this makes `regexp2` line up with PCRE, Rust, and Go.

**Comment by kovidgoyal** [comment]
Sounds good to me.
