### ISSUE TITLE
MatchString() timeout stuck

### ISSUE THREAD

**Issue by mcy1475369** [dlclark/regexp2#75]
**Description of the problem**：
I want to match a string of file paths, using "^/([a-zA-Z0-9_-]+/?) +$" is wrong and causes the execute() function to loop out.
**example func**：
```
package main

import (
	"fmt"

	regexp "github.com/dlclark/regexp2"
)

func main() {
	re := regexp.MustCompile("^/([a-zA-Z0-9_-]+/?)+$", regexp.ECMAScript)
	m, err := re.MatchString("/boot/firmware/clear_upgrade_pkg.sh")
	if err != nil {
		fmt.Println("err:", err)
	}
	fmt.Println("m:", m)
}

```
**Just replace it with another regular rule**：
```
 re := regexp.MustCompile("^/.*$", regexp.ECMAScript)
 // re := regexp.MustCompile("^/([a-zA-Z0-9_-]+/?)+[a-zA-Z0-9_-]+\\.[a-zA-Z]+$", regexp.ECMAScript)
```
**Expected results**：
String matching is also possible using the regular expression in the example code

**Comment by dlclark** [comment]
I'd recommend testing your regex's using https://regex101.com to debug them if they misbehave. Using this site you'd see that using the Python engine you get a catastrophic backtracking error and with C# you get a timeout as well.  Even Go doesn't match anything with the provided regex and input text--which is significant since Go's engine can't have catastrophic backtracking. 

The issue is that your file path sample includes a dot and that's not an allowed character. If you add that to the allowed charset then it'll work `^/([a-zA-Z0-9_\-\.]+/?)+$` However, every time you give that regex input with something that's not expected  there's a chance you'll get catastrophic backtracking again (with a timeout). Since it's risky to use a regex with a repeating charset with an optional terminator I recommend you either tighten your pattern a lot OR even better, if you need parse file paths I recommend you use the `path/filepath` package.
