### ISSUE TITLE
FR: support Marshal/Unmarshal

### ISSUE THREAD

**Issue by hunshcn** [dlclark/regexp2#76]
This will come in handy for building configurations

**Comment by dlclark** [comment]
What's the use case for adding this?

To me a Regexp is made up of 2 parts: pattern text and the options for running that pattern. This only serializes the pattern text and leaves the options unknown, so Marshal/Unmarshal isn't really a roundtrip of a Regexp instance. There are lots of options for overcoming this, but I'd need to know more about the use cases to help inform the design.

**Comment by hunshcn** [comment]
In order to construct configuration files more conveniently.
The regexp of the stdlib also implements Marshal/Unmarshal, however it is not as powerful as regexp2.

**Comment by dlclark** [comment]
The stdlib regex package doesn't support the wide range of options that regexp2 does, so it doesn't face the options problem that regexp2 does.  

Thinking about it some more I think the underlying problem is that not all the regexp2 options are settable in the pattern itself, so if you wanted to use RE2 compatibility mode, ECMAScript mode, or a Right-to-left pattern in a nested, marshaled Regexp it wouldn't be possible.

Today most options can be set within the pattern itself (e.g. `(?i)` for IgnoreCase) but the "top level only" options (`RE2`, `ECMAScript`, and `RightToLeft`) cannot be set this way. Maybe the fix is to add support for these "top level only" options to be at the start of the pattern and document that the marshal functionality requires the options to be embedded in the pattern itself with the `(?option)` syntax.
